/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GetAppRouteImport } from './routes/get-app'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TripRouteImport } from './routes/trip'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as PlaceSlugRouteImport } from './routes/place.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAppRoute = GetAppRouteImport.update({
  id: '/get-app',
  path: '/get-app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const PlaceSlugRoute = PlaceSlugRouteImport.update({
  id: '/place/$slug',
  path: '/place/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/get-app': typeof GetAppRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/saved': typeof SavedRoute
  '/trip': typeof TripRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/get-app': typeof GetAppRoute
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/saved': typeof SavedRoute
  '/trip': typeof TripRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/get-app': typeof GetAppRoute
  '/guides': typeof GuidesRouteWithChildren
  '/login': typeof LoginRoute
  '/plan': typeof PlanRoute
  '/saved': typeof SavedRoute
  '/trip': typeof TripRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/events'
    | '/explore'
    | '/get-app'
    | '/guides'
    | '/login'
    | '/plan'
    | '/saved'
    | '/trip'
    | '/guides/$slug'
    | '/place/$slug'
    | '/guides/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/events'
    | '/explore'
    | '/get-app'
    | '/login'
    | '/plan'
    | '/saved'
    | '/trip'
    | '/guides/$slug'
    | '/place/$slug'
    | '/guides'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/events'
    | '/explore'
    | '/get-app'
    | '/guides'
    | '/login'
    | '/plan'
    | '/saved'
    | '/trip'
    | '/guides/$slug'
    | '/place/$slug'
    | '/guides/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  GetAppRoute: typeof GetAppRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlanRoute: typeof PlanRoute
  SavedRoute: typeof SavedRoute
  TripRoute: typeof TripRoute
  PlaceSlugRoute: typeof PlaceSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-app': {
      id: '/get-app'
      path: '/get-app'
      fullPath: '/get-app'
      preLoaderRoute: typeof GetAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/place/$slug': {
      id: '/place/$slug'
      path: '/place/$slug'
      fullPath: '/place/$slug'
      preLoaderRoute: typeof PlaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  GetAppRoute: GetAppRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LoginRoute: LoginRoute,
  PlanRoute: PlanRoute,
  SavedRoute: SavedRoute,
  TripRoute: TripRoute,
  PlaceSlugRoute: PlaceSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
